name: CI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          script: |
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S systemctl stop gobot-backend
            cd ${{ secrets.SERVER_DEPLOY_DIR }}
            git pull origin main
            /usr/local/go/bin/go build
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S systemctl start gobot-backend
